### ISSUE TITLE
Application failed to serve

### ISSUE THREAD

**Issue by kevinyang372** [kevinyang372/codeEval#7]
The application log shows that `AttributeError: 'NoneType' object has no attribute 'drivername'

Deployment log
```
7:03:36 PM codeEval: Triggering recycle (preview mode disabled).
7:03:36 PM codeEval: Deployment successful.
7:03:41 PM: Deployment to "codeEval" completed.
7:04:23 PM: "codeEval" reported a critical error: Exception
```

**Comment by kevinyang372** [comment]
Seems like the app environment has no driver for mysql and thus the sqlalchemy fails to initiate properly.

**Comment by kevinyang372** [comment]
```
2020-11-18T23:17:08.009855778Z Updated PYTHONPATH to ':/antenv/lib/python3.8/site-packages'
2020-11-18T23:17:13.032486055Z [2020-11-18 23:17:13 +0000] [43] [INFO] Starting gunicorn 20.0.4
2020-11-18T23:17:13.046602066Z [2020-11-18 23:17:13 +0000] [43] [INFO] Listening at: http://0.0.0.0:8000 (43)
2020-11-18T23:17:13.046623067Z [2020-11-18 23:17:13 +0000] [43] [INFO] Using worker: sync
2020-11-18T23:17:13.058387410Z [2020-11-18 23:17:13 +0000] [45] [INFO] Booting worker with pid: 45
2020-11-18T23:17:16.567462338Z [2020-11-18 23:17:16 +0000] [45] [ERROR] Exception in worker process
2020-11-18T23:17:16.567515640Z Traceback (most recent call last):
2020-11-18T23:17:16.567547341Z   File "/opt/python/3.8.5/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2020-11-18T23:17:16.567556941Z     worker.init_process()
2020-11-18T23:17:16.567564741Z   File "/opt/python/3.8.5/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
2020-11-18T23:17:16.567572542Z     self.load_wsgi()
2020-11-18T23:17:16.567579542Z   File "/opt/python/3.8.5/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2020-11-18T23:17:16.567587542Z     self.wsgi = self.app.wsgi()
2020-11-18T23:17:16.567594942Z   File "/opt/python/3.8.5/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
2020-11-18T23:17:16.567602543Z     self.callable = self.load()
2020-11-18T23:17:16.567609843Z   File "/opt/python/3.8.5/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2020-11-18T23:17:16.567617443Z     return self.load_wsgiapp()
2020-11-18T23:17:16.567624643Z   File "/opt/python/3.8.5/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2020-11-18T23:17:16.567632543Z     return util.import_app(self.app_uri)
2020-11-18T23:17:16.567639744Z   File "/opt/python/3.8.5/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
2020-11-18T23:17:16.567647244Z     mod = importlib.import_module(module)
2020-11-18T23:17:16.567654544Z   File "/opt/python/3.8.5/lib/python3.8/importlib/__init__.py", line 127, in import_module
2020-11-18T23:17:16.567662344Z     return _bootstrap._gcd_import(name[level:], package, level)
2020-11-18T23:17:16.567670045Z   File "", line 1014, in _gcd_import
2020-11-18T23:17:16.567677945Z   File "", line 991, in _find_and_load
2020-11-18T23:17:16.567685745Z   File "", line 975, in _find_and_load_unlocked
2020-11-18T23:17:16.567693345Z   File "", line 671, in _load_unlocked
2020-11-18T23:17:16.567700845Z   File "", line 783, in exec_module
2020-11-18T23:17:16.567708346Z   File "", line 219, in _call_with_frames_removed
2020-11-18T23:17:16.567715946Z   File "/home/site/wwwroot/startup.py", line 1, in 
2020-11-18T23:17:16.567723546Z     from web import app
2020-11-18T23:17:16.567731046Z   File "/home/site/wwwroot/web/__init__.py", line 58, in 
2020-11-18T23:17:16.567738646Z     db.create_all()
2020-11-18T23:17:16.567745847Z   File "/antenv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 963, in create_all
2020-11-18T23:17:16.567753947Z     self._execute_for_all_tables(app, bind, 'create_all')
2020-11-18T23:17:16.567763047Z   File "/antenv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 955, in _execute_for_all_tables
2020-11-18T23:17:16.567776948Z     op(bind=self.get_engine(app, bind), **extra)
2020-11-18T23:17:16.567784648Z   File "/antenv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 896, in get_engine
2020-11-18T23:17:16.567792448Z     return connector.get_engine()
2020-11-18T23:17:16.567799448Z   File "/antenv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 556, in get_engine
2020-11-18T23:17:16.567806748Z     self._sa.apply_driver_hacks(self._app, info, options)
2020-11-18T23:17:16.567813849Z   File "/antenv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 830, in apply_driver_hacks
2020-11-18T23:17:16.567821549Z     if info.drivername.startswith('mysql'):
2020-11-18T23:17:16.567828949Z AttributeError: 'NoneType' object has no attribute 'drivername'
```

**Comment by kevinyang372** [comment]
https://code-eval-1.herokuapp.com/
